services:
  - type: web
    name: pythonmastery-backend
    env: node
    buildCommand: npm install --production=false && npm run build:backend
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000